public enum JobEnum {
	ALCHIMISTE, BIJOUTIER, BRICOLEUR, BUCHERON, CHASSEUR, CORDOMAGE, CORDONNIER, COSTUMAGE,
	FACOMAGE, FACONNEUR, FORGEMAGE, FORGERON, JOAILLOMAGE, MINEUR, PAYSAN, PECHEUR,
	SCULPTEMAGE, SCULPTEUR, TAILLEUR;	
}